In [1]:
import numpy as np

In [2]:
lst = [2, 5, 7, 8]

In [3]:
np.array(lst)

array([2, 5, 7, 8])

In [4]:
np.array([lst,lst])

array([[2, 5, 7, 8],
       [2, 5, 7, 8]])

In [5]:
np.array([ [2,4,6], [2,7,9] ])

array([[2, 4, 6],
       [2, 7, 9]])

In [6]:
np.array([ [2,4,6], [2,7,9], [3, -1, 6] ])

array([[ 2,  4,  6],
       [ 2,  7,  9],
       [ 3, -1,  6]])

In [7]:
10 * np.eye(4)

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])

In [11]:
np.zeros(shape=(4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
5 * np.ones(shape=(3,5))

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(-5,10)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [17]:
np.random.rand(2,3,6)

array([[[0.51263985, 0.63185176, 0.25105733, 0.93206326, 0.63208975,
         0.94643261],
        [0.13591481, 0.45402767, 0.16052229, 0.8941012 , 0.97503672,
         0.40300212],
        [0.97143153, 0.37460191, 0.91861642, 0.16460951, 0.13026589,
         0.49960838]],

       [[0.32662572, 0.38908149, 0.03618424, 0.08319422, 0.78963392,
         0.29654022],
        [0.93456018, 0.47282362, 0.667184  , 0.13668813, 0.02225886,
         0.93080235],
        [0.78541845, 0.05073959, 0.46683965, 0.41741706, 0.80706819,
         0.58203326]]])

In [20]:
np.arange(-5,10, 3)

array([-5, -2,  1,  4,  7])

In [22]:
np.arange(100, 10, -5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15])

In [23]:
np.linspace(0,20,20)

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

In [24]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [25]:
np.random.rand(2,3)

array([[0.36840119, 0.49906634, 0.79161417],
       [0.49984914, 0.67265763, 0.21817364]])

In [26]:
np.random.randint(10,50,5)

array([24, 48, 33, 44, 41])

In [27]:
mat = np.random.randn(4,5)

In [28]:
mat

array([[-0.24343217,  0.08849378, -1.64411654, -0.66410601,  0.17132567],
       [ 1.89098349, -0.01241134, -0.21456571, -1.81670343,  1.12856663],
       [ 0.5598503 ,  0.28952975, -0.16544015,  0.85811864, -0.43798945],
       [ 1.54763222, -1.18860872,  0.06658216, -0.16783586, -1.317844  ]])

In [29]:
type(mat)

numpy.ndarray

In [30]:
mat.size

20

In [31]:
mat.shape

(4, 5)

In [32]:
mat.reshape(2,10).shape

(2, 10)

In [33]:
mat.reshape(2,10)

array([[-0.24343217,  0.08849378, -1.64411654, -0.66410601,  0.17132567,
         1.89098349, -0.01241134, -0.21456571, -1.81670343,  1.12856663],
       [ 0.5598503 ,  0.28952975, -0.16544015,  0.85811864, -0.43798945,
         1.54763222, -1.18860872,  0.06658216, -0.16783586, -1.317844  ]])

In [34]:
mat.dtype

dtype('float64')

In [36]:
arr = np.arange(50,70)

In [37]:
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

In [38]:
arr.shape

(20,)

In [39]:
arr[4]

54

In [40]:
arr[18]

68